version: '3.8'
services:
    db:
        image: postgres
        container_name: ep-db
        environment:
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres 
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=shopping
            
        expose:
            - 5432
        volumes:
            - ./db:/var/lib/postgresql/data
        networks:
            - internal
    server:
        container_name: ep-server
        build:
            context: ./
            dockerfile: Dockerfile
        command: bash -c "go build -o app && ./app"
        volumes:
            - './:/app/server'
        ports:
            - '8080:8000'
        depends_on: 
            - db
        networks:
            - internal
        stdin_open: true
volumes:
    db:  
    server:
networks:
    internal:
      driver: bridge